name: Populate OnePiece database
on:
  # Every Friday at 10:00 UTC
  schedule:
    - cron: '0 5 * * 5'

   # Manual triggers
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

concurrency: 
  group: "onepiece"
  cancel-in-progress: true


env:
  REPO_BRANCH: onepiece

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo, using branch name
        uses: actions/checkout@v3
        if: github.event.inputs.git-ref == ''

      - name: Clone repo with ref
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.git-ref }}
        if: github.event.inputs.git-ref != ''

      - name: Run main python script
        run: |
          cp ./OnePieceTCG/main.py .

      - name: Commit to the repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          # "echo" returns true so the build succeeds, even if no changed files
          git commit --amend -m '[skip ci] updated one piece tcg database' || echo
          git push --force origin ${{ env.REPO_BRANCH }}
